export const CHANGE_DIRECTION = 'changeDirection';
export const MOVE_PLAYER = 'movePlayer';
export const PLACE_BOMB = 'placeBomb';
export const PLACE_WALL = 'placeWall';
export const DELETE_PLAYER = 'deletePlayer';
export const DELETE_WALL = 'deleteWall';
export const CREATE_PLAYER ='createPlayer';
export const LOGIN_PLAYER = 'loginPlayer';
export const CREATE_WALLS = 'createWalls';
